version: "3.9"

services:
  sixx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sixx-trading-engine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TRADING_MODE: DEMO
      PYTHONUNBUFFERED: "1"
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: python main.py
    ports:
      - "8501:8501"
